name: Build PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
          out/
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for Vercel
      run: npm run build-for-vercel
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          out/
          public/
        retention-days: 7
    
    - name: Comment PR
      uses: actions/github-script@v7
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Build succeeded! Artifacts are available for download from the workflow run.'
          })